CREATE TABLE `stock_data` (
  `id` int(12) unsigned NOT NULL AUTO_INCREMENT,
  `symbol` varchar(12) DEFAULT NULL,
  `series` varchar(12) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `prev_close` float DEFAULT NULL,
  `open_price` float DEFAULT NULL,
  `high_price` float DEFAULT NULL,
  `low_price` float DEFAULT NULL,
  `last_price` float DEFAULT NULL,
  `close_price` float DEFAULT NULL,
  `average_price` float DEFAULT NULL,
  `total_traded_quantity` int(12) unsigned DEFAULT NULL,
  `turnover_in_lacs` int(12) unsigned DEFAULT NULL,
  `no_of_trades` int(12) unsigned DEFAULT NULL,
  `deliverable_qty` int(12) unsigned DEFAULT NULL,
  `percent_dly_qt_to_traded_qty` int(12) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_symbol_series_date` (`symbol`,`series`,`date`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_date` (`date`),
  KEY `idx_open_price` (`open_price`),
  KEY `idx_close_price` (`close_price`),
  KEY `idx_agv` (`average_price`),
  KEY `idx_prev` (`prev_close`),
  KEY `idx_updated_at` (`updated_at`),
  KEY `idx_high_price` (`high_price`),
  KEY `idx_low_price` (`low_price`),
  KEY `idx_last_price` (`last_price`)
)
